### ISSUE TITLE
增加查询评测结果

### ISSUE THREAD

**Issue by langningchen** [boomzero/quicksubmit#1]
参考：
https://github.com/langningchen/OJTool/blob/84900ea81a982f12fc6f35ea06fe670e65259a1f/XMOJ.cpp#L237-L325

**Comment by boomzero** [comment]
emm, ~看不懂~

**Comment by boomzero** [comment]
also I am having problems with jsdom, it works, but when I compile the project the binary gives an error

**Comment by boomzero** [comment]
@langningchen is https://github.com/boomzero/quicksubmit/commit/d0680618940f652abb257aed2529075470a522cd enough?

**Comment by langningchen** [comment]
在爬取一个结果试试看

**Comment by boomzero** [comment]
Ok, also can you star this(

**Comment by boomzero** [comment]
> also I am having problems with jsdom, it works, but when I compile the project the binary gives an error

Well, I switched to `pkg` to fix this.

**Comment by boomzero** [comment]
@langningchen done...

**Comment by langningchen** [comment]
你也来卷工程了（

**Comment by boomzero** [comment]
> 你也来卷工程了（

@langningchen ~学校确定了就有心情写了~

**Comment by langningchen** [comment]
好吧，你确很厉害的啊，自招定了那个学校？

**Comment by boomzero** [comment]
> 好吧，你确很厉害的啊，自招定了那个学校？

@langningchen 上海市七宝中学

**Comment by boomzero** [comment]
swx 进了复附浦东

**Comment by langningchen** [comment]
知道

**Comment by boomzero** [comment]
@langningchen So? I think my implementation(giving a link for users to click on) is better.

**Comment by langningchen** [comment]
I've forgot what I said because it has been a long time.
