### ISSUE TITLE
[Tracking] port to deno

### ISSUE THREAD

**Issue by boomzero** [boomzero/quicksubmit#2]
bun -> node.js -> deno

**Comment by boomzero** [comment]
<img width="569" alt="image" src="https://github.com/boomzero/quicksubmit/assets/85378277/21694f2a-383e-4433-8040-9c8e66dff3fd">

@langningchen qwq...

**Comment by langningchen** [comment]
😕

**Comment by boomzero** [comment]
It has to pass `deno lint`

**Comment by boomzero** [comment]
done
